#!/usr/bin/env bash
# install nginx and serve
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Restarting nginx
sudo service nginx restart
