#!/usr/bin/env bash
## install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install haproxy -y

echo "
backend my_backend
    listen load_balancer
    bind *:80
    balance roundrobin
    server 362645-web-01 100.24.72.53:80 check
    server 362645-web-02 54.146.94.92:80 check
" >> /etc/haproxy/haproxy.cfg

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
